### PR TITLE
bug fix .github directory processing

### LINKED ISSUE #190: is_git_metadata incorrectly detects .github/xxx files as git metadata
While templating out a repo with GitHub action workflow that has a templated `{{project-name}}` referenced I noticed that the workflow file wasn't getting processed. I believe that's because it considers [any path containing `.git` in any part of its name to be git metadata](https://github.com/ashleygwilliams/cargo-generate/blob/d123ea95f598246e2184bb4a035c4a109c075235/src/template.rs#L135)

I'd be happy to jump in an fix but I'd be curious about when the next release cycle will run so I can know when I can start depending on the fix.

### PR DESCRIPTION
**Pull request by softprops**
fixes #190

### CODE REVIEW

File: tests/integration/basics.rs [hunk 1]
```diff
@@ -757,3 +757,28 @@ fn it_doesnt_warn_with_neither_config_nor_ignore() {
...
+        .arg("--git")
+        .arg(template.path())
+        .arg("-n")
+        .arg("foobar-project")
+        .current_dir(&dir.path())
+        .assert()
+        .success()
+        .stdout(predicates::str::contains("Done!").from_utf8());
+
+    assert!(dir
```
Comment (softprops) [inline tests/integration/basics.rs]: this tests fails on master because this file actually contains `{{project-name}}` because it exists in a directory that just happens to start with `.git` but is actually `.github`

**Comment by softprops** [comment]
@ashleygwilliams let me know what you think

**Comment by softprops** [comment]
@ashleygwilliams curtesy ping. I know you're probably busy. Let me know if you're looking for maintainers I'd be interested in helping moving some of these open issues forward

**Comment by ashleygwilliams** [comment]
hey! looking now and also YES! i'd love some help :)

**Comment by softprops** [comment]
Awesome I have some experience in this area

I work on https://github.com/softprops/porteurbars but have put that down now that this exisits and from a former life I worked on https://github.com/foundweekends/giter8

File: tests/integration/basics.rs [hunk 2]
```diff
@@ -757,3 +757,26 @@ fn it_doesnt_warn_with_neither_config_nor_ignore() {
...
+        .arg("--git")
+        .arg(template.path())
+        .arg("-n")
+        .arg("foobar-project")
+        .current_dir(&dir.path())
+        .assert()
+        .success()
+        .stdout(predicates::str::contains("Done!").from_utf8());
+
+    assert_eq!(dir.read("foobar-project/.github/foo.txt"), "foobar-project");
```
Comment (softprops) [inline tests/integration/basics.rs]: I should note that I wrote a failing test first. this previously evaluated to '{{project-name}}' because `.github` contains the string `.git`
