### PR TITLE
fix crate_name

### LINKED ISSUE #41: {{crate_name}} isn't being turned to snake_case
```
$ cargo new --lib my-template
     Created library `my-template` project

$ cd my-template/

$ cat Cargo.toml # <-- edited to have name be {{project-name}}
[package]
name = "{{project-name}}"
version = "0.1.0"
authors = ["Nick Fitzgerald <fitzgen@gmail.com>"]

[dependencies]

$ mkdir tests

$ echo 'extern crate {{crate_name}};' > tests/tests.rs

$ git add .

$ git commit -m "initial"
[master (root-commit) 5db8b7e] initial
 4 files changed, 17 insertions(+)
 create mode 100644 .gitignore
 create mode 100644 Cargo.toml
 create mode 100644 src/lib.rs
 create mode 100644 tests/tests.rs

$ cd ..

$ cargo-generate --git my-template --name my-project-with-hyphens
⠁
 Done! New project created /tmp/my-project-with-hyphens

$ cd my-project-with-hyphens/

$ cargo test
   Compiling my-project-with-hyphens v0.1.0 (file:///tmp/my-project-with-hyphens)
error: expected one of `;` or `as`, found `-`
 --> tests/tests.rs:1:16
  |
1 | extern crate my-project-with-hyphens;
  |                ^ expected one of `;` or `as` here

error: aborting due to previous error

error: Could not compile `my-project-with-hyphens`.
warning: build failed, waiting for other jobs to finish...
error: build failed
```

### PR DESCRIPTION
**Pull request by ashleygwilliams**
fixes #41 and #34

### CODE REVIEW

File: tests/integration/basics.rs [hunk 1]
```diff
@@ -40,3 +39,35 @@ authors = ["{{authors}}"]
...
+        .arg("--name")
+        .arg("foobar-project")
+        .current_dir(&dir.path())
+        .assert()
+        .success()
+        .stdout(predicates::str::contains("Done!").from_utf8());
+
+    assert!(
+        dir.read("foobar-project/main.rs")
+            .contains("foobar_project")
```
Comment (fitzgen) [inline tests/integration/basics.rs]: maybe assert that it also *doesn't* contain "foobar-project"?

Comment (ashleygwilliams) [reply tests/integration/basics.rs]: oh good call

Comment (ashleygwilliams) [reply tests/integration/basics.rs]: (i did that manually, so i don't know why i didn't think to add it. thank u!)
